### ISSUE TITLE
Rule name convention

### ISSUE THREAD

**Issue by matheuss** [sindresorhus/awesome-lint#10]
Proposal: the rules should be renamed from `awesome-rule-name` to `awesome/rule-name`. 

With this we will follow what is done on [ESlint](http://eslint.org) ☺️

**Comment by sindresorhus** [comment]
Does `remark-lint` actually support that? // @wooorm

**Comment by wooorm** [comment]
Havent tested but I believe so!

It may interfere with the fact that `awesome-rule-name` and `awesomeRuleName` are treated the same though, not sure if `awesome/rule-name` gets the same treatment.
