### ISSUE TITLE
Are you open to adding instructions for GitHub Actions

### ISSUE THREAD

**Issue by RayBB** [sindresorhus/awesome-lint#115]
Hey there,

I see you have some notes about setting up to run this with Travis.

It may be worth adding a quick note about how easy it is to setup with GitHub actions. [Here](https://github.com/RayBB/awesome-social-enterprise/blob/main/.github/workflows/main.yml)'s an example of how it can be done.

If you'd like me to make a PR for this let me know :) 

Thanks

**Comment by sindresorhus** [comment]
Sure, but should be without all those comments.
