### ISSUE TITLE
Proposal: allow for a TOC-silent "Footnotes" section at README's bottom.

### ISSUE THREAD

**Issue by kdeldycke** [sindresorhus/awesome-lint#117]
I felt the need of adding a `Footnotes` section in the very bottom of my Awesome list at: https://github.com/kdeldycke/awesome-falsehood/commit/d8db15ad0c6b0acaea1e6da1f48ea4a5922d4118#diff-0730bb7c2e8f9ea2438b52e419dd86c9

@sindresorhus would that be a good idea to have that [footnotes grouped together like this at the bottom](https://github.com/kdeldycke/awesome-falsehood/blob/d8db15ad0c6b0acaea1e6da1f48ea4a5922d4118/readme.md#footnotes)? If so, should I create a PR to propose [ignoring that section in the TOC alongside `Contributing` and `Licence`](https://github.com/sindresorhus/awesome-lint/blob/fe139d82d319023afefef0c8667a1d6fd2ef4ada/rules/toc.js#L15-L20) ?

**Comment by sindresorhus** [comment]
Sure

**Comment by kdeldycke** [comment]
A PR is ready for review at: #118.
