### ISSUE TITLE
no-emphasis-as-heading causing problems

### ISSUE THREAD

**Issue by RyanZim** [sindresorhus/awesome-lint#14]
The `no-emphasis-as-heading` rule doesn't like this:

> # Awesome npm scripts [![Awesome](https://cdn.rawgit.com/sindresorhus/awesome/d7305f38d29fed78fa85652e3a63e154dd8e8829/media/badge.svg)](https://github.com/sindresorhus/awesome)
> [![Travis branch](https://img.shields.io/travis/RyanZim/awesome-npm-scripts/master.svg?maxAge=2592000?style=plastic)](https://travis-ci.org/RyanZim/awesome-npm-scripts)
>
> > Everything awesome related to npm scripts and using npm as a build tool.
>
> *You might also like [awesome-npm](https://github.com/sindresorhus/awesome-npm).*
> 
> **Notice: I'm currently too busy to actively expand this list; therefore, I've decided to make this an [OPEN Open Source Project](http://openopensource.org). Individuals making significant and valuable contributions are given commit-access to the project to contribute as they see fit.**
> 
> ## Contents
> ...

https://github.com/RyanZim/awesome-npm-scripts

I understand this rule makes sense in most cases, but this case isn't one of them. The emphasis has nothing to do with the heading; it's just a bold notice that happens to come right before the top heading.

Would like thoughts/suggestions/discussion on this.

**Comment by sindresorhus** [comment]
That sounds like a bug indeed. Might want to post it here: https://github.com/wooorm/remark-lint/issues

// @wooorm

**Comment by RyanZim** [comment]
Finally got the issue filed: https://github.com/wooorm/remark-lint/issues/139

**Comment by RyanZim** [comment]
Closing as per https://github.com/wooorm/remark-lint/issues/139#issuecomment-294911981
