### ISSUE TITLE
Double Link detection when second link in a disabled block

### ISSUE THREAD

**Issue by derekmurawsky** [sindresorhus/awesome-lint#145]
### Scenario

I have a section for awesome lists and a section at the end where I give thanks to @sindresorhus for creating the idea of the awesome list. I wrapped that thanks section with a `<!--lint disable double-link -->` & `<!--lint enable double-link -->` and that works to suppress the double link notification for that particular instance of the link.

However, I still get a double-link error for the first instance of the link in the awesome list section above it. I have to add a `<!--lint ignore double-link -->` to that one as well to pass the linter.

### Desired behavior

If I wrap a link with `<!--lint disable double-link -->` & `<!--lint enable double-link -->` or use `<!--lint ignore double-link -->` it should not report as an occurence at all and should not report another link, elsewhere in the document, as a double link.

### Specific Example

See repo: https://github.com/derekmurawsky/dereks-awesome-list/blob/377d498e84f23d12c473bf5b66f3762fa65d3641/README.md?plain=1 Line 25-26 and line 52-54. I feel I should only need one `<!--lint ignore double-link -->`.  Alternatively, there should be a way to have an allowlist for things that may be commonly reference.

**Comment by sindresorhus** [comment]
This should be reported to https://github.com/Scrum/remark-lint-double-link

**Comment by derekmurawsky** [comment]
Oh, will do! Thanks!
