### ISSUE TITLE
Error caused by two dashes in item

### ISSUE THREAD

**Issue by liyansong2018** [sindresorhus/awesome-lint#146]
Awesome lint uses ` - ` to separate item link and description by default. Therefore, if item name also contains a dash, it will be considered an error. As if awesome list contributor didn't respect the guidlines?

README.md
```
- [ArcGIS location services - Postman Workspace](https://www.postman.com/arcgis-developer/workspace/arcgis-location-services) - Official Postman collections to work with the Geocoding & Search API, Routing & Directions API, Demographics & GeoEnrichment API, Data hosting and more.
```

awesome-lint
```shell
  README.md:43:126
  ✖  43:126  List item link and description must be separated with a dash  remark-lint:awesome-list-item
```

From: https://github.com/Esri/awesome-arcgis-developer/runs/5556738428?check_suite_focus=true

**Comment by hhkaos** [comment]
Thanks @liyansong2018, [it is now fixed](https://github.com/Esri/awesome-arcgis-developer/runs/5640614749?check_suite_focus=true). Sorry for the oversight!

**Comment by liyansong2018** [comment]
😃 The author doesn't seem to declare that there can't be dashes in the name, so I'm not sure whether this issue should be closed.

**Comment by hhkaos** [comment]
I understand 👍
