### ISSUE TITLE
Tests fail locally on Mac

### ISSUE THREAD

**Issue by cvan** [sindresorhus/awesome-lint#15]
According to the [Travis CI build history](https://travis-ci.org/sindresorhus/awesome-lint/builds), the builds are passing fine on Travis CI. Locally, I'm getting these errors when running the tests:

<details>
<pre><code>% npm test                                           /opt/awesome-lint (master)

> awesome-lint@0.1.0 test /opt/awesome-lint
> xo && ava

  rules/badge.js:19:7
  ⚠  19:7   Blocks are nested too deeply (5).                     max-depth

  index.js:10:11
  ⚠  35:19  Unexpected todo comment.                              no-warning-comments
  ✖  10:11  Unexpected chained assignment.                        no-multi-assign

  config.js:4:1
  ⚠  21:2   Unexpected todo comment.                              no-warning-comments
  ⚠  29:2   Unexpected todo comment.                              no-warning-comments
  ⚠  34:2   Unexpected todo comment.                              no-warning-comments
  ⚠  47:2   Unexpected todo comment.                              no-warning-comments
  ✖   4:1   Comments should not begin with a lowercase character  capitalized-comments
  ✖   7:2   Unnecessarily quoted property reset found.            quote-props
  ✖  63:2   Comments should not begin with a lowercase character  capitalized-comments
  ✖  64:2   Unnecessarily quoted property external found.         quote-props

  6 warnings
  5 errors
npm ERR! Test failed.  See above for more details.</code></pre>
</details>
<br>

<img width="568" alt="screen shot 2017-04-05 at 9 14 07 pm" src="https://cloud.githubusercontent.com/assets/203725/24737613/d8cb867e-1a44-11e7-96f9-fb1950b9c6ed.png">

<hr>

<dl>
  <dt>Operating system</dt>
  <dd>Mac OS X El Capitan, Version 10.11.2 (15C50)</dd>
  <dt>`node` version</dt>
  <dd>v7.0.0</dd>
  <dt>`npm` version</dt>
  <dd>3.10.8</dd>
</dl>

**Comment by SamVerschueren** [comment]
It's because the latest build dates from 8 months ago while XO got a new release in the meantime. Will fix it.

**Comment by cvan** [comment]
> It's because the latest build dates from 8 months ago while XO got a new release in the meantime. Will fix it.

Ah, gotcha - thanks. That explains the `Unexpected todo comment`, et. al. errors.
