### ISSUE TITLE
v0.18.4 broke linting from forks

### ISSUE THREAD

**Issue by rsamborski** [sindresorhus/awesome-lint#172]
Latest [v0.18.4](https://github.com/sindresorhus/awesome-lint/releases/tag/v0.18.4) release seems to have broken linting of code coming in from forks, examples:
 - [PR](https://github.com/GoogleCloudPlatform/awesome-google-cloud/pull/44/), [failed action](https://github.com/GoogleCloudPlatform/awesome-google-cloud/actions/runs/6266616710/job/17017976450)
 - [PR](https://github.com/GoogleCloudPlatform/awesome-google-cloud/pull/45/), [failed action](https://github.com/GoogleCloudPlatform/awesome-google-cloud/actions/runs/6266613754/job/17017966226)

As a workaround I had to lock to previous version (v0.18.3) which passes correctly - [see here](https://github.com/GoogleCloudPlatform/awesome-google-cloud/actions/runs/6273084194/job/17035904419)

**Comment by sindresorhus** [comment]
// @hyperupcall

**Comment by hyperupcall** [comment]
I am able to reproduce - working on a fix

**Comment by hyperupcall** [comment]
This broke linting because the code did not take into account that `HEAD` may not point to a branch - it could be in a detached state. And this commonly occurs in Github Actions when `@actions/checkout` is used to clone a repository.

And...

**Comment by rsamborski** [comment]
@hyperupcall Thank you for a super fast fix. I have tested and confirmed that v0.18.5 works correctly with our repository.
