### ISSUE TITLE
Text "Github" should be written as "GitHub"

### ISSUE THREAD

**Issue by tzwel** [sindresorhus/awesome-lint#198]
Happens [here](https://github.com/grantcarthew/awesome-unique-id/blob/1d09007697b6fe9214b8e8af4d42a7ac933c5eac/README.md), at line 47

**Comment by DecimalTurn** [comment]
Not an issue here. The linter is working as intended. 
The official spelling is "GitHub" and you have it written as "Github".

**Comment by tzwel** [comment]
I didn't notice the uppercase H! Fair
