### ISSUE TITLE
Severities

### ISSUE THREAD

**Issue by wooorm** [sindresorhus/awesome-lint#2]
I intended `vfile#fail` only for fatal exceptions, which make a file no longer processable. Warnings, like those in [`badge.js#L23`](https://github.com/sindresorhus/awesome-lint/blob/14fc116c8ff54fc8a13c4a3b7527eb95fb87d400/rules/badge.js#L23), and [`badge.js#L34`](https://github.com/sindresorhus/awesome-lint/blob/14fc116c8ff54fc8a13c4a3b7527eb95fb87d400/rules/badge.js#L34), should use `vfile#warn`.

If you use `warn` instead of `fail`, it also means there’s no longer a reason to use `file.quiet = true`.

A slightly separate, but also quite related problem, is the `error` / `warn` / `message` labels in the reporters, which you’re currently handling in [`index.js#L35`](https://github.com/sindresorhus/awesome-lint/blob/8b12c141a5ee1f617e0dcb20ea1d00bc4a832999/index.js#L35). That’s something which I definitely want to include, but it’ll take some time, and I’m not sure where yet.

However, for now I suggest adding a new file, `severity.js` or something, which looks like `config.js`

```js
// ...
	'heading-style': true,
	'link-title-style': null,
	'list-item-bullet-indent': false,
	'list-item-content-indent': true
// ...
```

(each rule-id refers to the state its message’s `fatal` properties should have, `true` for `error`, `false` for `warning`, and `null` for `message`).

Then, in [`index.js#L35`](https://github.com/sindresorhus/awesome-lint/blob/8b12c141a5ee1f617e0dcb20ea1d00bc4a832999/index.js#L35), do something like:

```js
var severity = require('./severity');
var own = {}.hasOwnProperty;

// ...

messages.forEach(x => {
  x.fatal = own.call(severity, x.ruleId) ? severity[x.ruleId] : x.fatal;
});
```

**Comment by sindresorhus** [comment]
Good point. I think I'll wait implementing severities until there's an actual need. I plan on most if not every rule to me an error.
