### ISSUE TITLE
How to lint non-readme issues?

### ISSUE THREAD

**Issue by transitive-bullshit** [sindresorhus/awesome-lint#25]
Currently, `awesome-lint` only lints an awesome list's readme itself, but there are several very reasonable guidelines in place that extend beyond the scope of linting just the readme.

I propose that we also lint the following:
- Has been around for at least 30 days.
  - This should be pretty easy assuming we require the usage of `git`.
- The repo should have awesome-list & awesome as GitHub topics.
  - This should also be relatively easy if we require the usage of `git`.
- Not a duplicate.
  - This should probably be just a warning.
- Has contribution guidelines. `contributing.md`

My question is whether or not it makes sense to add this functionality to `awesome-lint` or possibly in a hypothetical parent project like `awesome-repo-lint`? Either way, I'm not sure exactly how some of these would fit into the current `vfile` output formatter scheme.

Thoughts?

**Comment by sindresorhus** [comment]
My idea with `awesome-lint` was that it was not supposed to be limited to just the readme. I think it makes sense to have these checks in `awesome-lint` too.

---

> Either way, I'm not sure exactly how some of these would fit into the current vfile output formatter scheme.

I haven't tried, but I think we could just report without a filename.

**Comment by transitive-bullshit** [comment]
Initial non-readme rules included in #29
