### ISSUE TITLE
Table of Contents rule

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/awesome-lint#4]
Would be useful to have a rule that ensures a correct `Contents` (TOC):
- Ensure the first section is named `Contents`.
- Ensure all the links point to existing sections with the same name.
- Ensure all sections are included except for the `License` section.
- Ensure the `Contents` list is maximum 2 levels. (People have a tendency of creating too big TOCs)

**Comment by matheuss** [comment]
• Ensure that the sections follow the order of the table
👍?

**Comment by sindresorhus** [comment]
> Ensure the sections follow the order of the table

👍

**Comment by RyanZim** [comment]
Naive Idea: If you are using `doctoc`, you could run `doctoc` on Travis and then assert that there is no `git diff` output.

**Comment by wooorm** [comment]
I went ahead and started work on this, for now, I have to following **working theories**:

* New external rules bundle: `remark-lint-toc`;
* `toc-name` rule to assert the value of the heading (e.g., `'Contents'`);
* `toc-required` to assert existence (e.g., `true`),
* `toc-position` to assert heading position (e.g., `2`);
* `toc-max-depth` to assert maximum of nested `listItem`s (e.g., `2`);
* `toc-exists` / `toc-real` / ??? to assert links in toc exist in document (e.g., `true`);
* a) `no-toc-license` assert no `license` is linked (e.g., `true`);
* b) `toc-exclude` assert the listed headings are not included (e.g., `[/^license$/i]`);

@sindresorhus / anyone else Thoughts?

**Comment by wooorm** [comment]
Some more thoughts:

* `toc-list-only` — do not use anything else than a list in the TOC;
* `toc-tight` / `toc-loose` / ??? — Whether or not to use tight list-items (those rendered without `<p>`);

Finally, `toc-exists`, mentioned before, is already checked by [`remark-validate-links`](https://github.com/wooorm/remark-validate-links)

**Comment by wooorm** [comment]
Even more:

* `toc-reference-later` — all links should point to headings after the ToC;
* `toc-min-contents` (e.g., `4`) — ToC should reference at least x headings, otherwise, don’t include a ToC.

**Comment by sindresorhus** [comment]
@wooorm Sounds good! :)

> b) toc-exclude assert the listed headings are not included (e.g., [/^license$/i]);

👍
