### ISSUE TITLE
CONTRIBUTING.md file is not recognized

### ISSUE THREAD

**Issue by angrykoala** [sindresorhus/awesome-lint#46]
Executing `awesome-lint` throws the error `Missing file contributing.md`. I currently have a CONTRIBUTING.md (uppercase) file and I guess the lint tool expects it to be in lowercase. However, [Github's contributing guidelines](https://blog.github.com/2012-09-17-contributing-guidelines/) clearly an uppercase name for this file.

**Comment by transitive-bullshit** [comment]
Thanks for the report @angrykoala 😄

This definitely looks like a bug on our end, as I agree that `CONTRIBUTING.md` should be case-insensitive.

**Comment by angrykoala** [comment]
I'm not sure but maybe changing this [here](https://github.com/sindresorhus/awesome-lint/blob/master/rules/contributing.js#L10) to a regex like `/(contributing|CONTRIBUTING)(\.md)?/` would cover all the cases (including markdown and not markdown files)?
