### ISSUE TITLE
Dockerfile?

### ISSUE THREAD

**Issue by uraimo** [sindresorhus/awesome-lint#48]
I don't know if this can be useful to someone else, but I've used the following Dockerfile to run the linter in its own enclosed container (I don't really used nodejs and don't need all the npm packages required permanently installed on my system):

```
FROM node:latest
ARG USER
ARG REPO

RUN npm install --global awesome-lint

RUN git clone https://github.com/${USER}/${REPO}.git

RUN cd ${REPO};awesome-lint
```

To launch it:

```
docker build -t awesome --build-arg USER=<gitusername> --build-arg REPO=<gitreponame> .
```

**Comment by sindresorhus** [comment]
That looks very inefficient, unless Docker does some good caching.

**Comment by uraimo** [comment]
I was more interested in keeping this contained than anything else, if repeating the install step is an issue, saving the image after the npm install step (just a few additional Mb in a separate layer on top of nodejs's official image) would make it a bit more practical for repeated usage.

**Comment by sindresorhus** [comment]
Publish the instruction or Dockerfile as separate repo/gist and we can link to it from the readme.
