### ISSUE TITLE
List item style rule

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/awesome-lint#5]
The style is:

```
- [Name](Link) - Description.
```

The rule should:
- Ensure the link and description are delimited with `-`.
- Ensure the description starts with an uppercase.
- Ensure the description ends in a dot `.`.

**Comment by wooorm** [comment]
Notes

1. 👍 
2. what about `[alpha](bravo) - iPhone`, or ``[alpha](bravo) - `code` ``?
3. How about `?` and `!`, such as in `[alpha](bravo) - Really cool!`

**Comment by matheuss** [comment]
@wooorm:
2. 👍 
3. `!` seems ok, but `?`? ` - [foo](bar] - say what?` 😅

**Comment by sindresorhus** [comment]
2\. Maybe it should be allowed if the first word is camelCased? ``[alpha](bravo) - `code` `` should be an exception.
3\. `!` should be allowed, but not `?`.

**Comment by matheuss** [comment]
Consider the following `test/fixtures/list-item.md`:

<img width="214" alt="screen shot 2016-08-01 at 6 59 11 pm" src="https://cloud.githubusercontent.com/assets/4721750/17310332/09ca0860-581a-11e6-8cff-9f575f2ac632.png">

And the folowing `rules/list-item.js`: 

```js
visit(ast, 'list', (node, index) => {
   console.log(node);
   console.log('-------');
   console.log('list size:', node.children.length);
   done();
});
```
And the following output:

![screen shot 2016-08-01 at 6 59 53 pm](https://cloud.githubusercontent.com/assets/4721750/17310346/20c4d2ca-581a-11e6-8a8c-a4f95abfe178.png)

@wooorm: Why does `unist-util-visit` says that the list goes from line 7 to 11 (which is good for what we are trying to achieve with this rule), but only retuns that the valid `listItem`s as children of the list: 😰 Should I open an issue at `unist-util-visit`?

**Comment by wooorm** [comment]
That has nothing to do with `unist-util-visit`, rather, with how markdown is parsed.

Take a look at this:

```md
- [foo](bar) - baz
-> [foo](bar) - baz
- [foo](bar) - baz
-> [foo](bar) - baz
```

This renders, on GH, as:

- [foo](bar) - baz
-> [foo](bar) - baz
- [foo](bar) - baz
-> [foo](bar) - baz

Looks like two list-items to me!

P.S. Where’s `done` coming from?

**Comment by matheuss** [comment]
Hmmm, good catch. So for a begin, I'm going to test if there's two list items separated by more than 1 line. If so, there's one item :) 

PS: 
```js
'use strict';
const visit = require('unist-util-visit');

module.exports = (ast, file, language, done) => {
   visit(ast, 'list', (node, index) => {
      console.log(node);
      console.log('-------');
      console.log('list size:', node.children.length);

      done();
   });
};

```
😅

**Comment by matheuss** [comment]
Success!

![screen shot 2016-08-01 at 7 53 03 pm](https://cloud.githubusercontent.com/assets/4721750/17311402/8a6a8560-5821-11e6-90c2-9ee1f8749509.png)

Just need to check for the last item of the list. WIP PR coming soon! 😊
