### ISSUE TITLE
License rule

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/awesome-lint#6]
Need a rule to ensure a license is included and that it's one of the Creative Commons licenses.

https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license

**Comment by wooorm** [comment]
Is there any reason to *not* use CC0? Are there awesome lists using non-CC0 licenses?

People are of course free to create projects named `awesome-foo` and the like, but to add them to the list it could be required that CC0 is used?

**Comment by sindresorhus** [comment]
No reason that I know of other than license ignorance.

> People are of course free to create projects named awesome-foo and the like, but to add them to the list it could be required that CC0 is used?

Yes, or [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/).

**Comment by wooorm** [comment]
> No reason that I know of other than license ignorance.

👍 That’s where this linter comes in!

> Yes, or CC BY 4.0.

So something like the following:

* Require `license` section;
* Require paragraph in license section;
* Either:
  * Require first paragraph in license section to match `/^(CC BY 4\.0\.|CC0)\s+(\(c\)|©)\s/`;
  * Require first paragraph in license section to contain a link to CC BY 4 or CC0, which contains a badge image.

**Comment by sindresorhus** [comment]
👍 

Here's how the CC0 one looks like in practice: https://github.com/sindresorhus/awesome-nodejs#license
