### ISSUE TITLE
Exclude names when they are inline as a domain name

### ISSUE THREAD

**Issue by NewAlexandria** [sindresorhus/awesome-lint#71]
I've been linting and updating some awesome-list PRs, and I've found that there are a number that are failing because `github.com`, `youtube.com`, etc do not lint correctly.  It makes total sense that stand-alone (noun-like) usages of these names/brands should format in a way that looks well.  Domain names, though, are case agnostic by standard, and at very least should not raise linting errors.

also `https://GitHub.com/newalexandria/dotfiles/` just looks less attractive than `https://github.com`.

I'd like to open a PR that fixes this, with tests.  

I'll probably aim to do that in the next couple days, unless @sindresorhus 	or someone here flags that as undesirable.

**Comment by transitive-bullshit** [comment]
This looks like very solid feedback; would you mind posting some specific examples of the input & output from awesome-lint for context?

Thanks!

**Comment by NewAlexandria** [comment]
I've opened a PR for the conversation about this. 👆
