### ISSUE TITLE
Lint some canonical lists in awesome-lint CI

### ISSUE THREAD

**Issue by transitive-bullshit** [sindresorhus/awesome-lint#75]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2440%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/awesome-lint/issues/75)

It's hard to understand how some PRs will affect the output for `awesome-lint` on general awesome lists or to know if they'll introduce additional false errors.

It would help my confidence a lot while reviewing PRs if the CI for `awesome-lint` included some tests that ran `awesome-lint` on a variety of well-written, canonical awesome lists like [awesome-nodejs](https://github.com/sindresorhus/awesome-nodejs).

This can be viewed as adding **integration tests** for `awesome-lint`.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Sponsors (Total: $40.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($40.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/awesome-lint/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by itaisteinherz** [comment]
Should the tests run on the live version of the lists (hosted on GitHub) or on a locally stored version?

**Comment by transitive-bullshit** [comment]
Great question -- let's start with the locally stored version to ensure reproducibility between runs.

This won't be able to test some rules like the newly introduced `awesome/github`, but I think that's an acceptable tradeoff for now.

Thanks!

**Comment by TiagoDanin** [comment]
@transitive-bullshit Can I add compatibility with Travis CI, using the environment variable `TRAVIS_REPO_SLUG`[*](https://docs.travis-ci.com/user/environment-variables/) to get the url.

----

But `awesome/git-repo-age` will fail on Travis CI. Solution? If we use the Github API also in `awesome/git-repo-age` and we could get the date with the value of `created_at`.

**Comment by transitive-bullshit** [comment]
@TiagoDanin good thoughts all around, though I'd prefer to keep the first version of these integration tests as simple as possible.

We can add support for external rules like `awesome/github` and `awesome/git-repo-age` later.

**Comment by itaisteinherz** [comment]
> But `awesome/git-repo-age` will fail on Travis CI.

Why is that? We can store the awesome lists' repos as test fixtures, including the `.git` directories, which should allow `awesome/git-repo-age` to work as expected.

**Comment by itaisteinherz** [comment]
Some lists we could start off with

- [awesome-nodejs](https://github.com/sindresorhus/awesome-nodejs)
- [awesome-cross-platform-nodejs](https://github.com/bcoe/awesome-cross-platform-nodejs)
- [awesome-ios](https://github.com/vsouza/awesome-ios) - seems like there are lots of edge-cases here, which would allow us to test various new rules.
- [awesome-macOS](https://github.com/iCHAIT/awesome-macOS)
- [awesome-javascript](https://github.com/sorrycc/awesome-javascript)
- [awesome-swift](https://github.com/matteocrippa/awesome-swift)
- [awesome-vue](https://github.com/vuejs/awesome-vue)
- [awesome-nextjs](https://github.com/unicodeveloper/awesome-nextjs)

**Comment by sindresorhus** [comment]
This is a good idea. 👍

**Comment by chinesedfan** [comment]
How about mocking some API results? Including `.git` seems weird.

**Comment by notlmn** [comment]
That would be another thing to handle, git submodules should fine if I'm not wrong.
