### ISSUE TITLE
`awesome/github` tests failing only on Travis

### ISSUE THREAD

**Issue by notlmn** [sindresorhus/awesome-lint#81]
For some reason the `awesome/github` test only fails on Travis builds, but not on local runs.

I even pinned `awesome-lint` version to `0.10.0` in `package.json` moving from `*`. That didn't fix this too.

#### Local run
![image](https://user-images.githubusercontent.com/37769974/57789694-103ffd80-7757-11e9-9b0b-9503cc82f706.png)

#### Travis build
![image](https://user-images.githubusercontent.com/37769974/57789576-d8d15100-7756-11e9-939a-d6d640ec89c8.png)

Travis URL: https://travis-ci.org/notlmn/awesome-icons

**Comment by ebraminio** [comment]
Same issue here https://travis-ci.org/ebraminio/awesome-qsharp/builds/533174434 for https://github.com/ebraminio/awesome-qsharp

**Comment by TiagoDanin** [comment]
Confirmed, problem with [Rate Limit](https://developer.github.com/v3/#rate-limiting). 
I'll add an error message to this problem...

Use token in Travi CI
1. Creating a token [here](https://github.com/settings/tokens/new)
2. Open settings in TraviCI
3. Put your token in environment variables (`github_token`)
![image](https://user-images.githubusercontent.com/5731176/57855892-1e773380-77c2-11e9-9b77-71017b02e1f8.png)
