### ISSUE TITLE
You should enforce trailing slashes

### ISSUE THREAD

**Issue by jpswade** [sindresorhus/awesome-lint#94]
A lack of trailing slashes will result in two calls to the web server, rather than 1.

It's more correct to provide the whole URL, including the trailing slash.

**Comment by sindresorhus** [comment]
Can you link to a source for that?

**Comment by jpswade** [comment]
Sure, https://tools.ietf.org/html/rfc2616

**Comment by jpswade** [comment]
Perhaps I wasn't clear.

If their web server always redirects to add a trailing slash, you should add the trailing slash so that it doesn't have to do the redirect.

Including a trailing slash when creating anchors (links) can [reduce load](https://web.archive.org/web/20120119022421/http://www.standardzilla.com/2007/07/09/dont-forget-your-trailing-slash/), as it means the web server won’t have to redirect you there.

Essentially, it's always more correct to provide the whole URL, to avoid the extra redirect.

**Comment by sindresorhus** [comment]
That article is ancient and it also talks about paths, not hostname part. I'm happy to consider it, but I'd like proof that it's actually correct.

**Comment by transitive-bullshit** [comment]
This shouldn't affect most PWAs, and afaict it doesn't affect nginx and apache either as two very common .

With that being said, I'd also love to see some concrete proof one way or the other. 😄
